import { api } from './api'
import type { ActiveSession, BodyWeightEntry, BodyWeightInput, BodyWeightGoal, DashboardData, DayInput, ExerciseInput, PreviousExercisePerformance, PlanDetails, PlanSummary, SessionDetails, SetInput, WorkoutDay, PlannedExercise, WorkoutSet } from '../types/dashboard'

export const dashboardService = {
  me: () => api<string>('/Auth/me'),
  bodyWeight: () => api<BodyWeightEntry[]>('/BodyWeight'),
  bodyWeightGoal: () => api<BodyWeightGoal>('/BodyWeight/goal'),
  createBodyWeight: (body: BodyWeightInput) => api<BodyWeightEntry>('/BodyWeight', 'POST', body),
  updateBodyWeight: (id: number, body: BodyWeightInput) => api<BodyWeightEntry> (`/BodyWeight/${id}`, 'PUT', body),
  deleteBodyWeight: (id: number) => api(`/BodyWeight/${id}`, 'DELETE'),
  updateBodyWeightGoal: (goalWeightKg: number | null) => api<BodyWeightGoal>('/BodyWeight/goal','PUT',{ goalWeightKg }),
  dashboard: () => api<DashboardData>('/Dashboard'),
  plan: (id: number) => api<PlanSummary>(`/StrengthPlans/${id}`),
  fullPlan: (id: number) => api<PlanDetails>(`/StrengthPlans/${id}/full`),
  versions: (id: number) => api<PlanSummary[]>(`/StrengthPlans/${id}/versions`),
  createPlan: (name: string) => api<PlanSummary>('/StrengthPlans', 'POST', { name }),
  publish: (id: number) => api(`/StrengthPlans/${id}/publish`, 'PUT'),
  newVersion: (id: number) => api<PlanSummary>(`/StrengthPlans/${id}/new-version`, 'POST'),
  deletePlan: (id: number) => api(`/StrengthPlans/${id}`, 'DELETE'),
  addDay: (planId: number, body: DayInput) => api<WorkoutDay>(`/StrengthPlans/${planId}/days`, 'POST', body),
  updateDay: (id: number, body: DayInput) => api<WorkoutDay>(`/StrengthPlans/days/${id}`, 'PUT', body),
  deleteDay: (id: number) => api(`/StrengthPlans/days/${id}`, 'DELETE'),
  addExercise: (dayId: number, body: ExerciseInput) => api<PlannedExercise>(`/StrengthPlans/days/${dayId}/exercises`, 'POST', body),
  updateExercise: (id: number, body: ExerciseInput) => api<PlannedExercise>(`/StrengthPlans/exercises/${id}`, 'PUT', body),
  deleteExercise: (id: number) => api(`/StrengthPlans/exercises/${id}`, 'DELETE'),
  finishExercise: (id: number) => api(`/WorkoutSessions/exercises/${id}/finish`, 'PUT'),
  activeSession: () => api<ActiveSession>('/WorkoutSessions/active'),
  session: (id: number) => api<SessionDetails>(`/WorkoutSessions/${id}`),
  previousPerformance: (sessionId: number) => api<PreviousExercisePerformance[]>(`/WorkoutSessions/${sessionId}/previous-performance`),
  start: (dayId: number) => api<{ id: number }>(`/WorkoutSessions/days/${dayId}/start`, 'POST'),
  addSet: (id: number, body: SetInput) => api<WorkoutSet>(`/WorkoutSessions/exercises/${id}/sets`, 'POST', body),
  updateSet: (id: number, body: SetInput) => api<WorkoutSet>(`/WorkoutSessions/sets/${id}`, 'PUT', body),
  deleteSet: (id: number) => api(`/WorkoutSessions/sets/${id}`, 'DELETE'),
  finish: (id: number) => api(`/WorkoutSessions/${id}/finish`, 'PUT'),
}
